name: Promote Auto Image
on:
  workflow_dispatch:
    inputs:
      source:
        description: "Source environment (dev)"
        required: true
        default: dev
      target:
        description: "Target environment (staging or prod)"
        required: true
        type: choice
        options:
          - staging
          - prod

permissions:
  contents: write

jobs:
  promote-image:
   runs-on: ubuntu-latest
   
   steps: 
    - name: Checkout GitOps Repo
      uses: actions/checkout@v4
      with:
        repository: sureshkumar-devops/ecommerce-gitops
        token: ${{ secrets.GITOPS_TOKEN }}    
        path: gitops
        fetch-depth: 0      
  
    - name: Promote Image
      run: |       
       if [ "${{ github.event.inputs.target }}" == "staging" ]; then
           SRC_BRANCH="dev"
           DEST_BRANCH="staging"
           SRC_ENV="dev"
           DEST_ENV="staging"
       else
           SRC_BRANCH="staging"
           DEST_BRANCH="master"                      
           SRC_ENV="staging"
           DEST_ENV="prod"
       fi
          
       echo "Source Branch: $SRC_BRANCH"
       echo "Destination Branch: $DEST_BRANCH" 
       echo "Source Environment: $SRC_ENV"
       echo "Destination Environment: $DEST_ENV"

       cd gitops
       git fetch origin      

       # Read tag from SOURCE branch
       git checkout origin/$SRC_BRANCH
        
       IMAGE_REPO=$(grep repository environments/$SRC/values.yaml | awk '{print $2}' | tr -d '"')
       IMAGE_TAG=$(grep tag environments/$SRC/values.yaml | awk '{print $2}' | tr -d '"')          

       echo "Found Image Tag: $IMAGE_TAG"
       echo "Promoting $IMAGE_REPO:$IMAGE_TAG from $SRC → $DEST"

       # Switch to destination branch
       git checkout $DEST_BRANCH

       # Update destination values.yaml
       sed -i "s|repository:.*|repository: $IMAGE_REPO|" environments/$DEST/values.yaml
       sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|" environments/$DEST/values.yaml          
       #sed -i "s/tag:.*/tag: $IMAGE_TAG/" environments/$DEST_ENV/values.yaml

       echo "Promoting $IMAGE_REPO from $SRC_ENV → $DEST_ENV"
       echo "Promoting $IMAGE_TAG from $SRC_ENV → $DEST_ENV"

    - name: Configure Git and Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add environments/$DEST/values.yaml

        if git diff --staged --quiet; then
           echo "No changes to commit"
        else
          git commit -m "Promote image to ${{ github.event.inputs.target }}"
          git push origin HEAD
        fi       
                 
  
     
